### ISSUE TITLE
relations should be a required field

### ISSUE THREAD

**Issue by stefanprobst** [InTaVia/InTaVia-Backend#136]
entity.relations and event.relations is a required field according to https://github.com/InTaVia/api-client/blob/main/src/models.ts#L98 and https://github.com/InTaVia/api-client/blob/main/src/models.ts#L109

**Comment by sennierer** [comment]
but its not in the swagger of the API right? and at least for the entities I would keep it that way. Why would an entity need relations to events (could be that we dont even know the date of birth). We could change it for the events though, given that those events need at least one related entity.

**Comment by stefanprobst** [comment]
we did agree on an api contract, can we please stick to that?

**Comment by sennierer** [comment]
ok, I can change the API for now, but in the long run we should think about changing that to optional as I am pretty sure we will exclude a lot of entities eg from BiographyNET via making relations required (although obviously entities that dont have relations are also not very interesting)

**Comment by sennierer** [comment]
:) sure, got that completely wrong thought of `list.len() > 0` vs `None`
I will change that
