### ISSUE TITLE
allow searching for partial matches without asterisk

### ISSUE THREAD

**Issue by stefanprobst** [InTaVia/InTaVia-Backend#140]
currently, searching on entity/event/vocabulary-entry label fields, via `?q=` search param, the backend only matches either full words, or requires to add an asterisk.

for example: 

```
https://intavia-backend.acdh-dev.oeaw.ac.at/v2/api/entities/search/?q=klim
```

will find nothing, but

```
https://intavia-backend.acdh-dev.oeaw.ac.at/v2/api/entities/search/?q=klimt
```

will find "Klimt", as will

```
https://intavia-backend.acdh-dev.oeaw.ac.at/v2/api/entities/search/?q=klim%2A
```

this seems unintuitive - and is especially confusing in edit forms, where we want to have autocompletes for vocabulary-based fields. currently, typeing "a" in a "occupations" autocomplete returns 0 results. users are required to type "a*".

**Comment by sennierer** [comment]
Given the implementation of full text search in Blazegraph we would need to add wildcards server-side to the sparql query. However, that would mean that an exact search is no longer possible. Should we allow for exact searches when " is used?

**Comment by stefanprobst** [comment]
yep makes sense to me
