### ISSUE TITLE
query params should all be snake case

### ISSUE THREAD

**Issue by stefanprobst** [InTaVia/InTaVia-Backend#141]
the search params for `/api/events` already had these:

- `role`
- `role_id`
- `related_entities`
- `related_entities_id`

recently, the `/api/entities` endpoint gained:

- `relatedEntity`
- `relatedEntities_id`
- `eventRole`
- `eventRoles_id`

can we name these consistently?

**Comment by sennierer** [comment]
@stefanprobst I split this fix in two commits. first one fixed the new params to snake_case, second the already existing time filters. if that change in parameter names is a problem we can easily undo it.
