### ISSUE TITLE
APIS place-ids used in event-relations but not retrievable with entity endpoints

### ISSUE THREAD

**Issue by johannesliem** [InTaVia/InTaVia-Backend#163]
In many events APIS-places are linked in relations, but when using the ids to query the backend, the items cannot be found.

There are **1273** places when searching the `APIS dataset` for entity kind `place`:

`https://intavia-backend.acdh-dev.oeaw.ac.at/v2/api/entities/search?datasets=https%3A%2F%2Fapis.acdh.oeaw.ac.at%2Fdata%23v1&page=1&limit=500&kind=place`

There are **6363** places that cannot be found. Those places are retrieved from events that are related to entities, but not directly from event search endpoint, which currently does not work correctly, see https://github.com/InTaVia/InTaVia-Backend/issues/155. Hence, the actual number might be different for all events.

Here a few entries (id + decoded id):
```
["aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvMzA4Mw==, b'http://www.intavia.eu/apis/place/3083'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvMTQwNDA=, b'http://www.intavia.eu/apis/place/14040'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvMTA2MTc3, b'http://www.intavia.eu/apis/place/106177'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvMzgyNjQ=, b'http://www.intavia.eu/apis/place/38264'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvNTQxNQ==, b'http://www.intavia.eu/apis/place/5415'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvNzI4MDI=, b'http://www.intavia.eu/apis/place/72802'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvMTQyMDg=, b'http://www.intavia.eu/apis/place/14208'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvMTI3MzAz, b'http://www.intavia.eu/apis/place/127303'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvMTAxODA5, b'http://www.intavia.eu/apis/place/101809'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvODg0ODQ=, b'http://www.intavia.eu/apis/place/88484'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvMTI3MjM4, b'http://www.intavia.eu/apis/place/127238'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvMTA2Njkz, b'http://www.intavia.eu/apis/place/106693'",
 "aHR0cDovL3d3dy5pbnRhdmlhLmV1L2FwaXMvcGxhY2UvMjA4Mjg=, b'http://www.intavia.eu/apis/place/20828'",
... ]
```

**Comment by sennierer** [comment]
tried some of those with the fixed events and entities endpoint and they resolved. Closing this for now.
