### ISSUE TITLE
[question] is EntityEventKind still a thing?

### ISSUE THREAD

**Issue by stefanprobst** [InTaVia/InTaVia-Backend#18]
might just be a data problem, but in example queries i'm not finding any 'entity.events[].kind`, so wanted to make sure this is still planned as an (optional) property of an event?

what i tried:

```
curl "https://intavia-backend.acdh-dev.oeaw.ac.at/api/entities/search?page=1&limit=50&q=Tesla&includeEvents=true" | jq '.results[].events[]?.kind'
```

**Comment by sennierer** [comment]
yes, thats still planned but missing in the current data. And at least speaking from our data its generated. We have Person -> RelationType -> Place in the original data. RelationType.name (or reverse_name) is the role and even.kind needs to be a combination of the relation class and the role. Eg "Person-Place, studierte in"
So we might want to think about getting rid of it? Or make it the relation class only?

**Comment by johannesliem** [comment]
Resolved by EntityEventRelations, EventEntityRelations, Event-Kind Vocabulary and Role Vocabulary
