### ISSUE TITLE
[linkedIds] apis linked ids do not resolve as expected

### ISSUE THREAD

**Issue by johannesliem** [InTaVia/InTaVia-Backend#194]
example: https://apis.acdh.oeaw.ac.at/entity/70682
resolves to: https://apis.acdh.oeaw.ac.at/accounts/login/?next=/apis/entities/entity/person/70682/detail
should this forward to: https://apis.acdh.oeaw.ac.at/person/70682 ?

**Comment by sennierer** [comment]
it should actually forward to https://apis.acdh.oeaw.ac.at/apis/entities/entity/person/70682/detail which it also does, but there shouldnt be any authentication required for the detail view.
it https://apis.acdh.oeaw.ac.at/apis/entities/entity/person/70682/detail holds the same information as https://apis.acdh.oeaw.ac.at/person/70682 but is the default APIS view which also has views for places etc...
I creat an issue in the apis webpage repo to lift the authentication for the detail views
