### ISSUE TITLE
some entity.place are missing a label

### ISSUE THREAD

**Issue by stefanprobst** [InTaVia/InTaVia-Backend#59]
for example: search for "schmölzer, jakob eduard" (https://www.intavia.eu/apis/personproxy/40293), who has a couple of events attached, one of which has a place property referring to "Wildon" (http://www.intavia.eu/apis/place/153417) which includes the place id, and `kind: "place"` but is missing a label.

**Comment by sennierer** [comment]
irrelevant as we agreed to move places to the relations (see #74 )
and probably a data quality problem
